module.exports.IndustrySector = {
    "Agriculture, Forestry, Fishing and Hunting":"農林漁業及び狩猟業",
    "Mining, Quarrying, and Oil and Gas Extraction":"鉱業，採石業，石油・ガス採掘業",
    "Construction":"建設業",
    "Manufacturing":"製造業",
    "Manufacturing":"製造業",
    "Manufacturing":"製造業",
    "Utilities":"公益事業",
    "Information":"情報産業",
    "Transportation and Warehousing":"運輸及び倉庫業",
    "Transportation and Warehousing":"運輸及び倉庫業",
    "Wholesale Trade":"卸売業",
    "Retail Trade":"小売業",
    "Retail Trade":"小売業",
    "Finance and Insurance":"金融及び保険業",
    "Real Estate and Rental and Leasing":"不動産業，レンタル及び リース業",
    "Professional, Scientific, and Technical Services":"専門的・科学的・技術的サービス業",
    "Accommodation and Food Services":"宿泊及び飲食業",
    "Arts, Entertainment, and Recreation":"芸術,娯楽及びレクリエーション 業",
    "Educational Services":"教育サービス業",
    "Health Care and Social Assistance":"医療及び社会福祉業",
    "NA":"NA",
    "Other Services (except Public Administration)":"その他のサービス業　 ないもの　（公務を除く）",
    "Public Administration":"公務",
    "Unknown":"Unknown"
}

module.exports.AttackVector = {
    "malware": "マルウェア",
    "hacking": "ハッキング",
    "social": "ソーシャル",
    "error": "エラー",
    "physical": "物理的",
    "misuse": "不正利用"
}

module.exports.AttackType = {
    "NA": "NA",
    "DOS/DDOS": "DOS/DDOS",
    "Ransomware": "ランサムウェア",
    "Worm": "ウァーム",
    "Misdelivery": "誤送信",
    "Loss": "紛失",
    "Phishing": "フィッシング",
    "SQL Injection": "SQLインジェクション",
    "Theft": "盗難",
    "Publishing Error": "誤表示",
    "Exploit Vulnerability": "脆弱性悪用",
    "Scam": "詐欺",
    "Brute Force": "ブルートフォース",
    "Backdoor": "バックドア",
    "Adware": "アドウェア",
    "Spam": "スパム",
    "Malfunction": "不具合",
    "Programming Error": "プログラミングエラー",
    "Trojan": "トロイの木馬",
    "Cross-Site Scripting": "クロスサイトスクリプティング",
    "Intentional Leakage": "意図的な漏れ",
    "Privilege abuse": "権限悪用",
    "Tampering": "改ざん",
    "Unknown":"Unknown"
}

module.exports.ActorType = {
    "external": "外部",
    "internal": "内部",
    "unknown": "不明"
}

module.exports.CompanyType = {
    "private": "未上場",
    "public": "上場",
    "neither": "どちらでもない"
}

module.exports.Region = {
    "Asia": "アジア",
    "Oceania": "大洋州",
    "North America": "北米",
    "Latin America and the Caribbean": "中南米",
    "Antartica":"南極",
    "Europe": "欧州",
    "Middle East": "中東",
    "Africa": "アフリカ",
    "Americas":"南北アメリカ"
}

module.exports.CountryFilter = {
    "United States of America":"アメリカ",
    "Spain":"スペイン",
    "Republic of Korea":"大韓民国",
    "Japan":"日本国",
    "India":"インド",
    "Germany":"ドイツ",
    "China":"中華人民共和国",
    "Singapore":"シンガポール",
    "France":"フランス",
    "United Kingdom":"イギリス"
}

module.exports.RegionCode = {
    "142":"Asia",
    "009":"Oceania",
    "019":"Americas",
    "010":"Antartica",
    "150":"Europe",
    "002":"Africa"
}

module.exports.SectorCode = {
    "11":"Agriculture, Forestry, Fishing and Hunting",
    "21":"Mining, Quarrying, and Oil and Gas Extraction",
    "23":"Construction",
    "31":"Manufacturing",
    "32":"Manufacturing",
    "33":"Manufacturing",
    "22":"Utilities",
    "51":"Information",
    "48":"Transportation and Warehousing",
    "49":"Transportation and Warehousing",
    "42":"Wholesale Trade",
    "44":"Retail Trade",
    "45":"Retail Trade",
    "52":"Finance and Insurance",
    "53":"Real Estate and Rental and Leasing",
    "54":"Professional, Scientific, and Technical Services",
    "72":"Accommodation and Food Services",
    "71":"Arts, Entertainment, and Recreation",
    "61":"Educational Services",
    "62":"Health Care and Social Assistance",
    "NA":"NA",
    "81":"Other Services (except Public Administration)",
    "92":"Public Administration",
    "Unknown":"Unknown"
}

module.exports.CountryCode = {
    "US": "United States of America",
    "ES": "Spain",
    "KR": "Korea, Republic of",
    "JP": "Japan",
    "IN": "India",
    "DE": "Germany",
    "CN": "China",
    "SG": "Singapore",
    "FR": "France",
    "GB": "United Kingdom",
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Aland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint-Barthelemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia",
    "BQ": "Bonaire, Saint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "Congo, Democratic Republic of the",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Cote d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cape Verde",
    "CW": "Curacao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Faeroe Islands",
    "FM": "Micronesia (Federated States of)",
    "FO": "Falkland Islands (Malvinas)",
    "GA": "Gabon",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard Island and McDonal Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IO": "British Virgin Islands",
    "IQ": "Iraq",
    "IR": "Iran (Islamic Republic of)",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "Korea, Democratic People's Republic of",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Lao People's Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova, Republic of",
    "ME": "Montenegro",
    "MF": "Saint Martin (French part)",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Macedonia, The former Yugoslav Republic of",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macao",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "Other": "Other",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestinian Territory, Occupied",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SH": "Saint Helena",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen Islands",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SX": "Sint Maarten (Dutch part)",
    "SY": "Syrian Arab Republic",
    "SZ": "Swaziland",
    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan, Province of China",
    "TZ": "Tanzania, United Republic of",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "Unknown": "Unknown",
    "VA": "Holy See",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela (Bolivarian Republic of)",
    "VG": "British Virgin Islands",
    "VI": "United States Virgin Islands",
    "VN": "Viet Nam",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna Islands",
    "WS": "Samoa",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "vZambia",
    "ZW": "Zimbabwe"
}